### ISSUE TITLE
Clarification on Audio File Sources for AudioSetCaps Dataset

### ISSUE THREAD

**Issue by SaraAlthubaiti** [JishengBai/AudioSetCaps#1]
Dear AudioSetCaps team,

Thank you for providing the AudioSetCaps dataset; it is incredibly valuable for audio research. I noticed in the dataset summary that there are 1,910,920 audio captions listed. Could you kindly clarify from where I can obtain the corresponding audio files for these captions?

<img width="489" alt="Screenshot 2024-12-22 at 6 44 30 PM" src="https://github.com/user-attachments/assets/025d791e-f06c-4853-a951-f0d1ec0bceb6" />

Specifically, could you please share a link or instructions for accessing these audio files?

I appreciate your guidance and support. Looking forward to your response.

Best regards,
Sara

**Comment by JishengBai** [comment]
Hi Sara,

Thank you for your interest in our dataset. To download the AudioSet recordings, please refer to the instructions under "Download dataset" in PANN's repo at https://github.com/qiuqiangkong/audioset_tagging_cnn.

**Comment by SaraAlthubaiti** [comment]
Great! thanks a lot!
That's really helped :)
